title: GreenXChange
date: April 2016
content: +++
How to get households in Singapore to actively recycle? 
&nbsp;
__Turn one man's trash into another man's treasure__
&nbsp;
We made use of an existing Cash for Trash programme and paired it up with Carousell to make recycling more fun and rewarding.
&nbsp;

  Creatives: Sean Tan and Ali Tan
  Client: Singapore Environment Council
+++
