title: The Bowtie That Binds
date: March 2016

Shashlik-01.jpg:
  description: Opening page on the menu, mimicking a newsletter report highlighting Shashlik's long, storied history (a.k.a I can do long copy)


content: +++
 Shashlik, a fixture in the Singapore food and beverage scene for 30 years, suddenly closed in 2015. Its demise was mourned by many, prompting the sons of one of the elderly staff to revive the restaurant in 2016. We were tasked to create a new brand identity, one that celebrates the fresh start while honouring the restaurant’s history.
  &nbsp; 
  Agency: Kinetic Design & Advertising
  Art: Clay Kuok, Leng Soh, Sean Tan
  Copy: Catherine Phua, Ali Tan
  Creative Director: Pann Lim
  Client: Shashlik  
+++