title: Tchotchkes
date: Jan 2016

01-Nerf.jpg:
  description: Activity booklet for kids (2016 - Kinetic)

02-Nerf.jpg:
  description: Activity booklet for kids (2016 - Kinetic)

03-KinetikaX.jpg:
  description: Rebranding of local fitness studio (2015 - Blak Labs)

content: +++
  Bits and bobs that I did over the years.
  &nbsp;
  Clients: NERF, Singapore Children's Society, Oramin Myannmar, SingTel
  Agencies: Kinetic Design & Advertising, Blak Labs, Geometry Global/OgilvyAction
  +++
