title: Adulting
date: December, 2016
content: +++
Localised Ben & Jerry's global "Adulting" campaign with a taste of Singapore. 
The final video was deployed on YouTube, Facebook and Instagram.

  &nbsp;
  Agency: Kinetic Design & Advertising
  Art: Gian Jonathan, Sean Tan
  Copy: Ali Tan
  Creative Director: Pann Lim
  Client: Ben & Jerry's 
+++