title: FSCA
date: March 2017

content: +++
We were invited to imagine what "Eating" would be like 50 years into the future. 
Inspired by our nation's obsession with bureacracy and food, we created a fictional food labelling system and organisation designed to give consumers full knowledge of how food in 2065 is made. 
We even created actual products displaying the practical application of these labels. 
&nbsp;

  Agency: Kinetic Design & Advertising
  Art: Gian Jonathan, Astri Nursalim, Sean Tiang, Leng Soh, Sean Tan
  Copy: Catherine Phua, Ali Tan
  Creative Director: Pann Lim
  Client: SINGAPLURAL / Black Design  
+++