title: Your Stage Now Live
date: August 2016

1-Chef.jpg:
  description: OOH poster

2-potter.jpg:
  description: OOH poster

3-Rocker.jpg:
  description: OOH poster

4-skateboarder.jpg:
  description: OOH poster

5-woodworker.jpg:
  description: OOH poster

6-yoga.jpg:
  description: OOH poster

7-TYC_Hoarding.jpg:
  description: Facebook fans submitted their ideas on how they liked to express themselves, and Tell Your Children turned their suggestions into a huge mural

content: +++
To celebrate the opening of Singapore and Southeast Asia's first Global Flagship Store on 2 September 2016, we invited all everyone to take the stage and inspire fellow Singaporeans.
&nbsp;
We kickstarted the campaign with a Brand Film which featured inspiring Singaporeans of all ages, and followed with an in-depth interview series about what makes them tick.
The campaign was rounded out with a collaborative billboard (illustrated by Tell Your Children), and a user-generated feed which showcased how Singaporeans expressed themselves through fashion, culture and craft.
&nbsp;
[See the site live here](http://hardworkby.us/ysnl/)
&nbsp;

  Agency: Kinetic Design & Advertising
  Art: Gian Jonathan, Astri Nursalim, Clay Kuok, Sean Tiang, Leng Soh, Sean Tan, Chris Leow
  Copy: Catherine Phua, Ali Tan
  Creative Director: Pann Lim
  Client: UNIQLO  
+++