title: Your Stage Now Live
date: August 2016
Ben-1.jpg:
  description: Introductory post on social media

Ben-2.jpg:
  description: Tongue-twister for Truffle Kerfuffle

Ben-3.jpg:
  description: Tongue-twister for Urban Bourbon

Ben-5.jpg:
  description: '#flavourtwist tongue-twister challenge'

Ben-6.jpg:
  description: Launch limited edition sleeve

Ben-7.jpg:
  description: Flavour Twist t-shirt and hoodie

Ben-8.jpg:
  description: Flavour Twist limited edition tote bag (because you need something to carry your ice-cream in...)

Ben-9.jpg:
  description: PR Kit for hungry media people

Ben-10.jpg:
  description: Launch Scoop Shop

content: +++
To celebrate the opening of Singapore and Southeast Asia's first Global Flagship Store on 2 September 2016, we invited all everyone to take the stage and inspire fellow Singaporeans.
&nbsp;
We kickstarted the campaign with a Brand Film which featured inspiring Singaporeans of all ages, and followed with an in-depth interview series about what makes them tick.
The campaign was rounded out with a collaborative billboard (illustrated by Tell Your Children), and a user-generated feed which showcased how Singaporeans expressed themselves through fashion, culture and craft.
&nbsp;
[See the site live here](http://hardworkby.us/ysnl/)
&nbsp;

  Agency: Kinetic Design & Advertising
  Art: Gian Jonathan, Astri Nursalim, Sean Tan, Andrew Lee
  Copy: Catherine Phua, Ali Tan
  Creative Director: Pann Lim
  Client: UNIQLO  
+++