title: MetalFest 2016
date: October 2016
1-MF.jpg:
  description: A series of three posters

2-MF.jpg:
  description: In Metal We Trust

3-MF.jpg:
  description: Ascend to Metaldom

4-MF.jpg:
  description: Slave to the Metal

5-MF.jpg:
  description: The campaign lived across multiple platforms


content: +++
For many creatives, winning a Gold, Silver or Bronze at award shows means winning a ‘metal’. Inspired by this, we reimagined Singapore’s annual creative award show, the Gong Show, as a ‘metal’ celebration. We titled it “MetalFest Gong 2016”.
Borrowing from heavy metal’s visual style, tone and manner, the MetalFest call to entry campaign played up creatives’ obsession with collecting metals.
All communications directed would-be participants to this specially created MetalFest website. Amidst powerful and driving heavy metal riffs, the site housed information about the award categories, the juries, and most crucially, the entry kit. The catch was, access was restricted* — and only true metalheads could unlock the site.
&nbsp;
&#42; Restricted Access when viewed on Google Chrome
&nbsp;
[See the site live here](http://www.metalfestgong2016.com)
&nbsp;
Agency: Kinetic Design & Advertising
Art: Gian Jonathan, Leng Soh, Clay Kuok, Astri Nursalim, Sean Tiang, Sean Tan, Andrew Lee, Chris Leow
Copy: Catherine Phua, Ali Tan
Creative Director: Pann Lim
Client: Creative Circle Awards  
+++