title: Flavour Twist

date: March 2017

Ben-1.jpg:
  description: Introductory post on social media

Ben-2.jpg:
  description: Tongue-twister for Truffle Kerfuffle

Ben-3.jpg:
  description: Tongue-twister for Urban Bourbon

Ben-5.jpg:
  description: '#flavourtwist tongue-twister challenge'

Ben-6.jpg:
  description: Launch limited edition sleeve

Ben-7.jpg:
  description: Flavour Twist t-shirt and hoodie

Ben-8.jpg:
  description: Flavour Twist limited edition tote bag (because you need something to carry your ice-cream in...)

Ben-9.jpg:
  description: PR Kit for hungry media people

Ben-10.jpg:
  description: Launch Scoop Shop

content: +++
Urban Bourbon and Truffle Kerfuffle.
Two new flavours by Ben & Jerry's created for sophisticated millennial tastebuds.
The problem? How can we can convince working adults that Ben & Jerry's is more than just cookie batter and junk food, without losing the brand's quirky personality?
This calls for a twist of epic proportions. 
&nbsp;

  Agency: Kinetic Design & Advertising
  Art: Gian Jonathan, Astri Nursalim, Sean Tan, Andrew Lee
  Copy: Catherine Phua, Ali Tan
  Creative Director: Pann Lim
  Client: Ben & Jerry's  
+++


