title: Say Yes
date: April 2017

FB_Toolkit-01.jpg:
  description: B2B Marketing Toolkit 

FB_Toolkit-02.jpg:
  description: We had to simplify complex data into byte-sized nuggets of information for busy marketers

FB_Toolkit-03.jpg:
  description:

FB_Toolkit-04.jpg:
  description:


content: +++
People are increasingly turning to mobile phones to learn what's happening with the world and with their friends. 
Advertisers on the other hand, have been slow to catch up with consumers' changing habits despite compelling stats which show that pairing Facebook with TV makes for more effective advertising.
So we devised a mobile-first campaign to win over their minds — by getting Facebook to win TV's heart.
&nbsp;
In a series of newsfeed ads and posts, we had Facebook proposing to TV in various dating scenarios, promising myriad benefits as a result of their union.
&nbsp;
We also brought the courtship to life using Facebook Canvas and Instagram Stories.
&nbsp;
Originally from Singapore, other markets were so smitten by the campaign they adopted it too.
&nbsp;
  Agency: Kinetic Design & Advertising
  Art: Gian Jonathan, Astri Nursalim, Sean Tan, Andrew Lee
  Copy: Catherine Phua, Ali Tan
  Creative Director: Pann Lim
  Client: Facebook Asia Pacific  
+++